const actionTypes = {
  EMAIL_VERIFICATION_REQUEST: "EMAIL_VERIFICATION_REQUEST",
  EMAIL_VERIFICATION_SUCCESS: "EMAIL_VERIFICATION_SUCCESS",
  EMAIL_VERIFICATION_FAILURE: "EMAIL_VERIFICATION_FAILURE",
  GET_INPUT: "GET_INPUT",
};

export default actionTypes;
