const actionTypes = {
  EMAIL_VERIFICATION_REQUEST: "EMAIL_VERIFICATION_REQUEST",
  EMAIL_VERIFICATION_SUCCESS: "EMAIL_VERIFICATION_SUCCESS",
  EMAIL_VERIFICATION_FAILURE: "EMAIL_VERIFICATION_FAILURE",

  GET_INPUT_PERSONAL_INFO: "GET_INPUT_PERSONAL_INFO",
  GET_INPUT_ADDRESS: "GET_INPUT_ADDRESS",
  GET_INPUT_MEASURMENTS: "GET_INPUT_MEASURMENTS",

  STEP_FORWARD: "STEP_FORWARD",
  STEP_BACK: "STEP_BACK",

  ERROR_HANDLING_PERSONAL_INFO: "ERROR_HANDLING_PERSONAL_INFO",
  ERROR_HANDLING_ADDRESS: "ERROR_HANDLING_ADDRESS",
  ERROR_HANDLING_MEASURMENTS: "ERROR_HANDLING_MEASURMENTS",
};

export default actionTypes;
