export const questions = {
  measurments: {
    height: "Zadajte svoju výšku",
    weight: "Zadajte svoju váhu",
  },
  goals: {
    timeToAchieveGoal: "Za aký čas by ste chceli dosiahnuť váš cieľ",
    importantGoal: "Ktorý pokrok je pre vás dôležitý",
  },
  exercises: {
    levelOfExercise: "Ohodnoťte vašu úroveň pri týchto cvikoch",
    currentlyTraining: "Cvičíte momentálne pravidelne?",
    typeOfExercises: "Vyplňte, ktorý typ pohybovej aktivity bežne robíte",
    descriptionOfTraining: "Popíšte váš tréning",
    favouriteSport: "Aký druh pohybu máte najradšej?",
    trainingDuration: "Ako dlho by mal trvať tréning?",
    trainingFrequency: "Ako často chcete do týždňa trénovať?",
  },
  lifestyle: {
    proffesion: "Aké je vaše povolanie?",
    levelOfMovementInWork: "Aká je vaša úroveň pohybovej aktivity pri vašom povolaní?",
    workOnShifts: "Pracujete na zmeny?",
    traveling: "Ako často cestujete na dlhšie vzdialenosti?",
    foodInvestment: "Koľko € by ste chceli týždenne investovať do potravín?",
    suplementInvestment: "Koľko € by ste chceli investovať o doplnkov výživy?",
    fastFood: "Koľko jedál si do týždňa objednáde v reštauráciách a fastfoodoch?",
    allergies: "Máte alergie?",
    allergiesList: "Napíšte alergiu a pridajte",
    suplements: "Užívate doplnky výživy?",
    suplementsList: "Napíšte doplnok a pridajte",
    unPopularFood: "Vypíšte jedlá, ktoré nemáte radi",
    popularFood: "Vypíšte jedlá, ktoré máte radi",
    qualities: "Ohodnotťe nasledujúce",
  },
  health: {
    healthProblems: "Máte zdravotné problémy?",
    medicals: "Užívate lieky?",
    injuries: "Máte zranenia?",
    problemsList: "Napíšte problém a pridajte",
    medicalsList: "Napíšte liek a pridajte",
    injuriesList: "Napíšte zranenie a pridajte",
  },
  additionalInfo: {
    priority: "Aká je vaša priorita?",
    requirements: "Máte špeciálne požiadavky, ktoré chcete pri spolupráci zohľadniť?",
    complaints: "Aké sú vaše najčastejšie sťažnosti z oblastí vášho zdravia, výživy a postavy?",
    expactations: "Čo očakávate od spolupráce so mnou?",
    relax: "Čo považujete za relax?",
  },
};
